services:
  - type: web
    name: three-section-jira-ui
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python launch_three_section.py"
    env:
      - key: FLASK_ENV
        value: production
      - key: PORT
        sync: false